In [8]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV,cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [4]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [10]:
# Select features and target variable
X = df[['pclass', 'sex', 'age', 'fare', 'embarked']]
y = df['survived']

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

models = [
    ('Random Forest',RandomForestClassifier(random_state=42)),
    ('Gradient Boost',GradientBoostingClassifier(random_state=42)),
    ('SVM',SVC(random_state=42))
]

best_model = None
best_accuracy = 0.0

for name, model in models:
    pipeline = Pipeline([
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('encoder',OneHotEncoder(handle_unknown='ignore')),
        ('model',model)
    ])

    scores =cross_val_score(pipeline,X_train,y_train,cv=5)

    mean_accuracy = scores.mean()

    pipeline.fit(X_train,y_train)

    # Make predictions on the test data
    y_pred = pipeline.predict(X_test)

    accuracy = accuracy_score(y_test,y_pred)

    print('Model :',name)
    print('Cross Validation Accuracy',mean_accuracy)
    print('Test Accuracy ',accuracy)
    print()

    if accuracy > best_accuracy:
        best_accuracy = accuracy
        best_model = pipeline

print("Best Model:" ,best_model)

Model : Random Forest
Cross Validation Accuracy 0.7991529597163399
Test Accuracy  0.8379888268156425

Model : Gradient Boost
Cross Validation Accuracy 0.8061952132374668
Test Accuracy  0.7988826815642458

Model : SVM
Cross Validation Accuracy 0.8160248202501723
Test Accuracy  0.8044692737430168

Best Model: Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder', OneHotEncoder(handle_unknown='ignore')),
                ('model', RandomForestClassifier(random_state=42))])